'use strict';

/** @type {{[k: string]: ModdedSpeciesData & {stage: string}}} */
let BattlePokedex = {
	botamon: {
		num: -2000,
		name: "Botamon",
		stage: "Fresh",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 57, atk: 33, def: 23, spa: 38, spd: 18, spe: 20},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dodomon: {
		num: -2001,
		name: "Dodomon",
		stage: "Fresh",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 51, atk: 38, def: 22, spa: 37, spd: 38, spe: 18},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	kuramon: {
		num: -2002,
		name: "Kuramon",
		stage: "Fresh",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 58, atk: 27, def: 20, spa: 27, spd: 21, spe: 22},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.005,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	poyomon: {
		num: -2003,
		name: "Poyomon",
		stage: "Fresh",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 63, atk: 21, def: 24, spa: 30, spd: 31, spe: 19},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	punimon: {
		num: -2004,
		name: "Punimon",
		stage: "Fresh",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 55, atk: 42, def: 21, spa: 29, spd: 21, spe: 29},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	yuramon: {
		num: -2005,
		name: "Yuramon",
		stage: "Fresh",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 22, def: 29, spa: 18, spd: 29, spe: 20},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	bukamon: {
		num: -2006,
		name: "Bukamon",
		stage: "In-Training",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 62, atk: 36, def: 24, spa: 35, spd: 27, spe: 38},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.007,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	dorimon: {
		num: -2007,
		name: "Dorimon",
		stage: "In-Training",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 63, atk: 41, def: 30, spa: 40, spd: 30, spe: 24},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	koromon: {
		num: -2008,
		name: "Koromon",
		stage: "In-Training",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 62, atk: 43, def: 31, spa: 31, spd: 31, spe: 24},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	motimon: {
		num: -2009,
		name: "Motimon",
		stage: "In-Training",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 60, atk: 41, def: 27, spa: 41, spd: 28, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.008,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	nyaromon: {
		num: -2010,
		name: "Nyaromon",
		stage: "In-Training",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 63, atk: 36, def: 22, spa: 38, spd: 24, spe: 29},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.008,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tanemon: {
		num: -2011,
		name: "Tanemon",
		stage: "In-Training",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 61, atk: 36, def: 26, spa: 26, spd: 29, spe: 28},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	tokomon: {
		num: -2012,
		name: "Tokomon",
		stage: "In-Training",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 58, atk: 34, def: 24, spa: 34, spd: 27, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	tsumemon: {
		num: -2013,
		name: "Tsumemon",
		stage: "In-Training",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 63, atk: 44, def: 27, spa: 44, spd: 28, spe: 27},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tsunomon: {
		num: -2014,
		name: "Tsunomon",
		stage: "In-Training",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 59, atk: 46, def: 28, spa: 33, spd: 28, spe: 32},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	agumon: {
		num: -2015,
		name: "Agumon",
		stage: "Rookie",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 48, def: 36, spa: 36, spd: 31, spe: 33},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	aruraumon: {
		num: -2016,
		name: "Aruraumon",
		stage: "Rookie",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 63, atk: 42, def: 36, spa: 41, spd: 36, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	betamon: {
		num: -2017,
		name: "Betamon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 49, atk: 44, def: 29, spa: 42, spd: 38, spe: 31},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	biyomon: {
		num: -2018,
		name: "Biyomon",
		stage: "Rookie",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 58, atk: 41, def: 31, spa: 41, spd: 29, spe: 42},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	clearagumon: {
		num: -2019,
		name: "ClearAgumon",
		stage: "Rookie",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 64, atk: 45, def: 38, spa: 45, spd: 36, spe: 33},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	demidevimon: {
		num: -2020,
		name: "DemiDevimon",
		stage: "Rookie",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 58, atk: 42, def: 39, spa: 43, spd: 39, spe: 37},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.008,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dokunemon: {
		num: -2021,
		name: "Dokunemon",
		stage: "Rookie",
		types: ["DG-Grass", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 62, atk: 46, def: 38, spa: 45, spd: 38, spe: 32},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	dorumon: {
		num: -2022,
		name: "Dorumon",
		stage: "Rookie",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 74, atk: 46, def: 39, spa: 45, spd: 39, spe: 30},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	elecmon: {
		num: -2023,
		name: "Elecmon",
		stage: "Rookie",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 46, def: 30, spa: 44, spd: 30, spe: 29},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	gabumon: {
		num: -2024,
		name: "Gabumon",
		stage: "Rookie",
		types: ["DG-Normal", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 34, spa: 48, spd: 34, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	goburimon: {
		num: -2025,
		name: "Goburimon",
		stage: "Rookie",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 69, atk: 48, def: 42, spa: 38, spd: 38, spe: 29},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	gomamon: {
		num: -2026,
		name: "Gomamon",
		stage: "Rookie",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 63, atk: 43, def: 38, spa: 43, spd: 36, spe: 32},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gotsumon: {
		num: -2027,
		name: "Gotsumon",
		stage: "Rookie",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 76, atk: 45, def: 46, spa: 47, spd: 35, spe: 28},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	kunemon: {
		num: -2028,
		name: "Kunemon",
		stage: "Rookie",
		types: ["DG-Grass", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 58, atk: 43, def: 39, spa: 42, spd: 39, spe: 30},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	modokibetamon: {
		num: -2029,
		name: "ModokiBetamon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 47, atk: 45, def: 29, spa: 42, spd: 39, spe: 32},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	muchomon: {
		num: -2030,
		name: "Muchomon",
		stage: "Rookie",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 55, atk: 41, def: 31, spa: 41, spd: 29, spe: 41},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	otamamon: {
		num: -2031,
		name: "Otamamon",
		stage: "Rookie",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 61, atk: 43, def: 27, spa: 41, spd: 36, spe: 31},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	palmon: {
		num: -2032,
		name: "Palmon",
		stage: "Rookie",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 60, atk: 43, def: 33, spa: 41, spd: 33, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	patamon: {
		num: -2033,
		name: "Patamon",
		stage: "Rookie",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 56, atk: 40, def: 32, spa: 38, spd: 32, spe: 44},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	penguinmon: {
		num: -2034,
		name: "Penguinmon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 43, def: 37, spa: 43, spd: 35, spe: 35},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	psychemon: {
		num: -2035,
		name: "Psychemon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 35, spa: 48, spd: 35, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	salamon: {
		num: -2036,
		name: "Salamon",
		stage: "Rookie",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 61, atk: 33, def: 32, spa: 44, spd: 34, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	shamanmon: {
		num: -2037,
		name: "Shamanmon",
		stage: "Rookie",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 68, atk: 43, def: 35, spa: 42, spd: 34, spe: 34},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	snowagumon: {
		num: -2038,
		name: "SnowAgumon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 57, atk: 44, def: 38, spa: 33, spd: 33, spe: 31},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	snowgoburimon: {
		num: -2039,
		name: "SnowGoburimon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 46, def: 36, spa: 36, spd: 32, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tentomon: {
		num: -2040,
		name: "Tentomon",
		stage: "Rookie",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 39, def: 41, spa: 43, spd: 35, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	toyagumon: {
		num: -2041,
		name: "ToyAgumon",
		stage: "Rookie",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 66, atk: 42, def: 41, spa: 42, spd: 39, spe: 32},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	tsukaimon: {
		num: -2042,
		name: "Tsukaimon",
		stage: "Rookie",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 59, atk: 41, def: 33, spa: 39, spd: 33, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	airdramon: {
		num: -2043,
		name: "Airdramon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 86, atk: 49, def: 54, spa: 47, spd: 53, spe: 55},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	akatorimon: {
		num: -2044,
		name: "Akatorimon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 92, atk: 56, def: 54, spa: 56, spd: 47, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	angemon: {
		num: -2045,
		name: "Angemon",
		stage: "Champion",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 55, def: 45, spa: 55, spd: 43, spe: 51},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	bakemon: {
		num: -2046,
		name: "Bakemon",
		stage: "Champion",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 91, atk: 36, def: 49, spa: 50, spd: 54, spe: 49},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	birdramon: {
		num: -2047,
		name: "Birdramon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 43, spa: 53, spd: 42, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	blackgatomon: {
		num: -2048,
		name: "BlackGatomon",
		stage: "Champion",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 85, atk: 42, def: 38, spa: 58, spd: 42, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	centarumon: {
		num: -2049,
		name: "Centarumon",
		stage: "Champion",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 88, atk: 56, def: 56, spa: 56, spd: 49, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	coelamon: {
		num: -2050,
		name: "Coelamon",
		stage: "Champion",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 96, atk: 52, def: 50, spa: 45, spd: 44, spe: 47},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	darkrizamon: {
		num: -2051,
		name: "Darkrizamon",
		stage: "Champion",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 93, atk: 66, def: 47, spa: 66, spd: 54, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	devimon: {
		num: -2052,
		name: "Devimon",
		stage: "Champion",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 97, atk: 46, def: 43, spa: 63, spd: 48, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dolphmon: {
		num: -2053,
		name: "Dolphmon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 86, atk: 48, def: 50, spa: 48, spd: 43, spe: 50},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dorugamon: {
		num: -2054,
		name: "Dorugamon",
		stage: "Champion",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 99, atk: 65, def: 59, spa: 63, spd: 58, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	drimogemon: {
		num: -2055,
		name: "Drimogemon",
		stage: "Champion",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 63, def: 55, spa: 55, spd: 48, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	flarerizamon: {
		num: -2056,
		name: "Flarerizamon",
		stage: "Champion",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 94, atk: 65, def: 45, spa: 65, spd: 52, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	frigimon: {
		num: -2057,
		name: "Frigimon",
		stage: "Champion",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 90, atk: 51, def: 59, spa: 51, spd: 58, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	fugamon: {
		num: -2058,
		name: "Fugamon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 66, def: 50, spa: 67, spd: 50, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garurumon: {
		num: -2059,
		name: "Garurumon",
		stage: "Champion",
		types: ["DG-Water", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 97, atk: 52, def: 46, spa: 59, spd: 45, spe: 48},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gatomon: {
		num: -2060,
		name: "Gatomon",
		stage: "Champion",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 88, atk: 42, def: 41, spa: 56, spd: 44, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	gekomon: {
		num: -2061,
		name: "Gekomon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 87, atk: 48, def: 46, spa: 48, spd: 49, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	geremon: {
		num: -2062,
		name: "Geremon",
		stage: "Champion",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 57, spa: 54, spd: 57, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	greymon: {
		num: -2063,
		name: "Greymon",
		stage: "Champion",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 99, atk: 67, def: 53, spa: 50, spd: 47, spe: 46},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	guardromon: {
		num: -2064,
		name: "Guardromon",
		stage: "Champion",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 100, atk: 54, def: 60, spa: 62, spd: 45, spe: 42},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.032,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	gururumon: {
		num: -2065,
		name: "Gururumon",
		stage: "Champion",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 94, atk: 52, def: 44, spa: 59, spd: 43, spe: 53},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	hyogamon: {
		num: -2066,
		name: "Hyogamon",
		stage: "Champion",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 96, atk: 65, def: 53, spa: 66, spd: 53, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	icedevimon: {
		num: -2067,
		name: "IceDevimon",
		stage: "Champion",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 94, atk: 59, def: 52, spa: 60, spd: 52, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	icemon: {
		num: -2068,
		name: "Icemon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 93, atk: 46, def: 60, spa: 48, spd: 59, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ikkakumon: {
		num: -2069,
		name: "Ikkakumon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 99, atk: 69, def: 56, spa: 64, spd: 55, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	junglemojyamon: {
		num: -2070,
		name: "JungleMojyamon",
		stage: "Champion",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 94, atk: 61, def: 54, spa: 53, spd: 54, spe: 48},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	kabuterimon: {
		num: -2071,
		name: "Kabuterimon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 98, atk: 55, def: 59, spa: 62, spd: 59, spe: 47},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	kokatorimon: {
		num: -2072,
		name: "Kokatorimon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 59, def: 44, spa: 59, spd: 38, spe: 46},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	kuwagamon: {
		num: -2073,
		name: "Kuwagamon",
		stage: "Champion",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 42, spa: 64, spd: 42, spe: 48},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	leomon: {
		num: -2074,
		name: "Leomon",
		stage: "Champion",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 69, def: 45, spa: 52, spd: 40, spe: 43},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meicoomon: {
		num: -2075,
		name: "Meicoomon",
		stage: "Champion",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 85, atk: 59, def: 40, spa: 59, spd: 41, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meramon: {
		num: -2076,
		name: "Meramon",
		stage: "Champion",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 99, atk: 70, def: 41, spa: 51, spd: 36, spe: 44},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	mikemon: {
		num: -2077,
		name: "Mikemon",
		stage: "Champion",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 90, atk: 43, def: 41, spa: 57, spd: 44, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	mojyamon: {
		num: -2078,
		name: "Mojyamon",
		stage: "Champion",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 92, atk: 55, def: 59, spa: 48, spd: 59, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	monochromon: {
		num: -2079,
		name: "Monochromon",
		stage: "Champion",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 99, atk: 66, def: 58, spa: 58, spd: 50, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	morishellmon: {
		num: -2080,
		name: "MoriShellmon",
		stage: "Champion",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 96, atk: 59, def: 58, spa: 59, spd: 51, spe: 39},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	mudfrigimon: {
		num: -2081,
		name: "MudFrigimon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 89, atk: 55, def: 58, spa: 55, spd: 56, spe: 38},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	nanimon: {
		num: -2082,
		name: "Nanimon",
		stage: "Champion",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 93, atk: 54, def: 49, spa: 62, spd: 37, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	ninjamon: {
		num: -2083,
		name: "Ninjamon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 45, spa: 55, spd: 45, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	nisedrimogemon: {
		num: -2084,
		name: "NiseDrimogemon",
		stage: "Champion",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 95, atk: 54, def: 53, spa: 47, spd: 46, spe: 44},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	numemon: {
		num: -2085,
		name: "Numemon",
		stage: "Champion",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 83, atk: 48, def: 42, spa: 44, spd: 56, spe: 40},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	ogremon: {
		num: -2086,
		name: "Ogremon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 66, def: 55, spa: 67, spd: 55, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	piddomon: {
		num: -2087,
		name: "Piddomon",
		stage: "Champion",
		types: ["DG-Fairy", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 87, atk: 59, def: 46, spa: 55, spd: 45, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	platinumsukamon: {
		num: -2088,
		name: "PlatinumSukamon",
		stage: "Champion",
		types: ["DG-Poison", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 55, spa: 61, spd: 57, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	redvegiemon: {
		num: -2089,
		name: "RedVegiemon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 93, atk: 59, def: 47, spa: 61, spd: 47, spe: 44},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	rockmon: {
		num: -2090,
		name: "Rockmon",
		stage: "Champion",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 61, def: 52, spa: 61, spd: 50, spe: 33},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	saberdramon: {
		num: -2091,
		name: "Saberdramon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 86, atk: 66, def: 42, spa: 55, spd: 41, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	sandyanmamon: {
		num: -2092,
		name: "SandYanmamon",
		stage: "Champion",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 91, atk: 46, def: 60, spa: 53, spd: 53, spe: 44},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	seadramon: {
		num: -2093,
		name: "Seadramon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 88, atk: 60, def: 52, spa: 61, spd: 55, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.021,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	shellmon: {
		num: -2094,
		name: "Shellmon",
		stage: "Champion",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 59, spa: 60, spd: 52, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shimaunimon: {
		num: -2095,
		name: "ShimaUnimon",
		stage: "Champion",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 81, atk: 54, def: 43, spa: 61, spd: 38, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	soulmon: {
		num: -2096,
		name: "Soulmon",
		stage: "Champion",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 91, atk: 29, def: 48, spa: 58, spd: 58, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	sukamon: {
		num: -2097,
		name: "Sukamon",
		stage: "Champion",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 92, atk: 48, def: 51, spa: 49, spd: 51, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tankmon: {
		num: -2098,
		name: "Tankmon",
		stage: "Champion",
		types: ["DG-Steel", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 59, spa: 65, spd: 44, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.035,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	togemon: {
		num: -2099,
		name: "Togemon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 63, def: 56, spa: 61, spd: 56, spe: 41},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	tyrannomon: {
		num: -2100,
		name: "Tyrannomon",
		stage: "Champion",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 65, def: 45, spa: 63, spd: 45, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	unimon: {
		num: -2101,
		name: "Unimon",
		stage: "Champion",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 56, def: 43, spa: 56, spd: 38, spe: 50},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.3,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	vegiemon: {
		num: -2102,
		name: "Vegiemon",
		stage: "Champion",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 89, atk: 46, def: 54, spa: 48, spd: 54, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	weedmon: {
		num: -2103,
		name: "Weedmon",
		stage: "Champion",
		types: ["DG-Grass", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 90, atk: 59, def: 48, spa: 60, spd: 48, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	yanmamon: {
		num: -2104,
		name: "Yanmamon",
		stage: "Champion",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 47, spa: 60, spd: 41, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	andromon: {
		num: -2105,
		name: "Andromon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 125, atk: 69, def: 72, spa: 76, spd: 53, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	angewomon: {
		num: -2106,
		name: "Angewomon",
		stage: "Ultimate",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 129, atk: 57, def: 52, spa: 76, spd: 57, spe: 66},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	beastmon: {
		num: -2107,
		name: "Beastmon",
		stage: "Ultimate",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 120, atk: 79, def: 52, spa: 69, spd: 46, spe: 70},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	blackweregarurumon: {
		num: -2108,
		name: "BlackWereGarurumon",
		stage: "Ultimate",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 128, atk: 75, def: 67, spa: 76, spd: 67, spe: 66},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	bluemeramon: {
		num: -2109,
		name: "BlueMeramon",
		stage: "Ultimate",
		types: ["DG-Fire", "DG-Water"],
		gender: "N",
		baseStats: {hp: 137, atk: 76, def: 57, spa: 77, spd: 57, spe: 62},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	digitamamon: {
		num: -2110,
		name: "Digitamamon",
		stage: "Ultimate",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 130, atk: 69, def: 76, spa: 51, spd: 68, spe: 50},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	dorugreymon: {
		num: -2111,
		name: "DoruGreymon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 135, atk: 79, def: 71, spa: 77, spd: 70, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.036,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	etemon: {
		num: -2112,
		name: "Etemon",
		stage: "Ultimate",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 119, atk: 66, def: 73, spa: 67, spd: 73, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garudamon: {
		num: -2113,
		name: "Garudamon",
		stage: "Ultimate",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 125, atk: 75, def: 58, spa: 75, spd: 57, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	gigadramon: {
		num: -2114,
		name: "Gigadramon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 134, atk: 72, def: 73, spa: 81, spd: 55, spe: 61},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	giromon: {
		num: -2115,
		name: "Giromon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 125, atk: 81, def: 60, spa: 71, spd: 60, spe: 56},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	iceleomon: {
		num: -2116,
		name: "IceLeomon",
		stage: "Ultimate",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 130, atk: 88, def: 60, spa: 66, spd: 53, spe: 58},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ladydevimon: {
		num: -2117,
		name: "LadyDevimon",
		stage: "Ultimate",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 126, atk: 58, def: 54, spa: 78, spd: 60, spe: 63},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	lillymon: {
		num: -2118,
		name: "Lillymon",
		stage: "Ultimate",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 122, atk: 65, def: 63, spa: 65, spd: 63, spe: 66},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.016,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	magnaangemon: {
		num: -2119,
		name: "MagnaAngemon",
		stage: "Ultimate",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 128, atk: 77, def: 46, spa: 70, spd: 60, spe: 66},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	mamemon: {
		num: -2120,
		name: "Mamemon",
		stage: "Ultimate",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 127, atk: 68, def: 68, spa: 75, spd: 51, spe: 59},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	megadramon: {
		num: -2121,
		name: "Megadramon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 131, atk: 79, def: 68, spa: 60, spd: 61, spe: 56},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	megakabuterimon: {
		num: -2122,
		name: "MegaKabuterimon",
		stage: "Ultimate",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 139, atk: 79, def: 70, spa: 59, spd: 62, spe: 55},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	megaseadramon: {
		num: -2123,
		name: "MegaSeadramon",
		stage: "Ultimate",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 75, def: 61, spa: 74, spd: 61, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	meicrackmon: {
		num: -2124,
		name: "Meicrackmon",
		stage: "Ultimate",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 110, atk: 77, def: 53, spa: 75, spd: 53, spe: 68},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meicrackmonvm: {
		num: -2125,
		name: "Meicrackmon VM",
		stage: "Ultimate",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 110, atk: 77, def: 53, spa: 75, spd: 53, spe: 68},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	metalgreymonvaccine: {
		num: -2126,
		name: "MetalGreymon Vaccine",
		stage: "Ultimate",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	metalgreymonvirus: {
		num: -2127,
		name: "MetalGreymon Virus",
		stage: "Ultimate",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	metalmamemon: {
		num: -2128,
		name: "MetalMamemon",
		stage: "Ultimate",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 123, atk: 76, def: 69, spa: 75, spd: 69, spe: 62},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	meteormon: {
		num: -2129,
		name: "Meteormon",
		stage: "Ultimate",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 135, atk: 65, def: 75, spa: 70, spd: 56, spe: 63},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	monzaemon: {
		num: -2130,
		name: "Monzaemon",
		stage: "Ultimate",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 134, atk: 53, def: 65, spa: 72, spd: 71, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	myotismon: {
		num: -2131,
		name: "Myotismon",
		stage: "Ultimate",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 136, atk: 57, def: 63, spa: 77, spd: 70, spe: 55},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	piximon: {
		num: -2132,
		name: "Piximon",
		stage: "Ultimate",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 118, atk: 65, def: 63, spa: 64, spd: 63, spe: 65},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shogungekomon: {
		num: -2133,
		name: "ShogunGekomon",
		stage: "Ultimate",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 72, def: 73, spa: 74, spd: 73, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	skullgreymon: {
		num: -2134,
		name: "SkullGreymon",
		stage: "Ultimate",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 138, atk: 85, def: 73, spa: 65, spd: 66, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	tekkamon: {
		num: -2135,
		name: "Tekkamon",
		stage: "Ultimate",
		types: ["DG-Steel", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 123, atk: 70, def: 67, spa: 62, spd: 67, spe: 60},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.05,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	vademon: {
		num: -2136,
		name: "Vademon",
		stage: "Ultimate",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 119, atk: 78, def: 52, spa: 72, spd: 69, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	vermilimon: {
		num: -2137,
		name: "Vermilimon",
		stage: "Ultimate",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 130, atk: 78, def: 73, spa: 68, spd: 64, spe: 57},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	warumonzaemon: {
		num: -2138,
		name: "WaruMonzaemon",
		stage: "Ultimate",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 133, atk: 53, def: 64, spa: 72, spd: 70, spe: 55},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.024,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	waruseadramon: {
		num: -2139,
		name: "WaruSeadramon",
		stage: "Ultimate",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 58, def: 56, spa: 77, spd: 61, spe: 59},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	weregarurumon: {
		num: -2140,
		name: "WereGarurumon",
		stage: "Ultimate",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 127, atk: 74, def: 59, spa: 74, spd: 58, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	whamon: {
		num: -2141,
		name: "Whamon",
		stage: "Ultimate",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 140, atk: 75, def: 71, spa: 75, spd: 70, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	zudomon: {
		num: -2142,
		name: "Zudomon",
		stage: "Ultimate",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 137, atk: 80, def: 72, spa: 80, spd: 70, spe: 51},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	alphamon: {
		num: -2143,
		name: "Alphamon",
		stage: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 185, atk: 107, def: 101, spa: 107, spd: 98, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.07,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackmetalgarurumon: {
		num: -2144,
		name: "BlackMetalGarurumon",
		stage: "Mega",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 184, atk: 99, def: 66, spa: 90, spd: 50, spe: 79},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.028,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackwargreymon: {
		num: -2145,
		name: "BlackWarGreymon",
		stage: "Mega",
		types: ["DG-Dark", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 188, atk: 101, def: 81, spa: 78, spd: 69, spe: 74},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	boltmon: {
		num: -2146,
		name: "Boltmon",
		stage: "Mega",
		types: ["DG-Steel", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 191, atk: 100, def: 84, spa: 75, spd: 76, spe: 73},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	cherubimonevil: {
		num: -2147,
		name: "Cherubimon Evil",
		stage: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 195, atk: 106, def: 63, spa: 96, spd: 86, spe: 78},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.035,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	cherubimongood: {
		num: -2148,
		name: "Cherubimon Good",
		stage: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 183, atk: 102, def: 69, spa: 92, spd: 92, spe: 75},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	devitamamon: {
		num: -2149,
		name: "Devitamamon",
		stage: "Mega",
		types: ["DG-Poison", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 184, atk: 99, def: 87, spa: 97, spd: 87, spe: 76},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	dorugoramon: {
		num: -2150,
		name: "Dorugoramon",
		stage: "Mega",
		types: ["DG-Steel", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 188, atk: 101, def: 83, spa: 99, spd: 100, spe: 72},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.064,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ebemon: {
		num: -2151,
		name: "Ebemon",
		stage: "Mega",
		types: ["DG-Steel", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 184, atk: 76, def: 67, spa: 98, spd: 79, spe: 66},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	herculeskabuterimon: {
		num: -2152,
		name: "HerculesKabuterimon",
		stage: "Mega",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 188, atk: 89, def: 91, spa: 104, spd: 90, spe: 80},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	hiandromon: {
		num: -2153,
		name: "HiAndromon",
		stage: "Mega",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 181, atk: 97, def: 82, spa: 87, spd: 61, spe: 74},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	lilithmon: {
		num: -2154,
		name: "Lilithmon",
		stage: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 191, atk: 58, def: 69, spa: 104, spd: 89, spe: 80},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	machinedramon: {
		num: -2155,
		name: "Machinedramon",
		stage: "Mega",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 189, atk: 90, def: 86, spa: 101, spd: 65, spe: 72},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	magnadramon: {
		num: -2156,
		name: "Magnadramon",
		stage: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 190, atk: 102, def: 84, spa: 101, spd: 87, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	marineangemon: {
		num: -2157,
		name: "MarineAngemon",
		stage: "Mega",
		types: ["DG-Water", "DG-Fairy"],
		gender: "N",
		baseStats: {hp: 170, atk: 52, def: 72, spa: 82, spd: 71, spe: 75},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	metaletemon: {
		num: -2158,
		name: "MetalEtemon",
		stage: "Mega",
		types: ["DG-Poison", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 171, atk: 75, def: 84, spa: 84, spd: 63, spe: 69},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	metalgarurumon: {
		num: -2159,
		name: "MetalGarurumon",
		stage: "Mega",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 182, atk: 97, def: 70, spa: 96, spd: 70, spe: 76},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.028,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	metalseadramon: {
		num: -2160,
		name: "MetalSeadramon",
		stage: "Mega",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 185, atk: 94, def: 62, spa: 83, spd: 82, spe: 70},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	ophanimon: {
		num: -2161,
		name: "Ophanimon",
		stage: "Mega",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 180, atk: 72, def: 86, spa: 104, spd: 85, spe: 80},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	phoenixmon: {
		num: -2162,
		name: "Phoenixmon",
		stage: "Mega",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 190, atk: 75, def: 75, spa: 100, spd: 82, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	princemamemon: {
		num: -2163,
		name: "PrinceMamemon",
		stage: "Mega",
		types: ["DG-Fairy", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 175, atk: 83, def: 87, spa: 82, spd: 87, spe: 69},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	raguelmon: {
		num: -2164,
		name: "Raguelmon",
		stage: "Mega",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 188, atk: 95, def: 66, spa: 92, spd: 101, spe: 84},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	rasielmon: {
		num: -2165,
		name: "Rasielmon",
		stage: "Mega",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 189, atk: 92, def: 66, spa: 95, spd: 101, spe: 84},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	rosemon: {
		num: -2166,
		name: "Rosemon",
		stage: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 171, atk: 89, def: 69, spa: 88, spd: 69, spe: 75},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.019,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	saberleomon: {
		num: -2167,
		name: "SaberLeomon",
		stage: "Mega",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 182, atk: 98, def: 70, spa: 97, spd: 70, spe: 77},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	seraphimon: {
		num: -2168,
		name: "Seraphimon",
		stage: "Mega",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 185, atk: 96, def: 62, spa: 107, spd: 81, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	venommyotismon: {
		num: -2169,
		name: "VenomMyotismon",
		stage: "Mega",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 190, atk: 105, def: 92, spa: 80, spd: 82, spe: 70},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.038,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	vikemon: {
		num: -2170,
		name: "Vikemon",
		stage: "Mega",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 193, atk: 100, def: 85, spa: 90, spd: 77, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	wargreymon: {
		num: -2171,
		name: "WarGreymon",
		stage: "Mega",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 187, atk: 100, def: 85, spa: 75, spd: 76, spe: 71},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	blackagumon: {
		num: -2172,
		name: "BlackAgumon",
		stage: "Rookie",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 64, atk: 49, def: 34, spa: 33, spd: 30, spe: 28},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackgabumon: {
		num: -2173,
		name: "BlackGabumon",
		stage: "Rookie",
		types: ["DG-Dark", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 65, atk: 51, def: 32, spa: 45, spd: 33, spe: 31},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackgreymon: {
		num: -2174,
		name: "BlackGreymon",
		stage: "Champion",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 98, atk: 68, def: 51, spa: 47, spd: 46, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	blackgarurumon: {
		num: -2175,
		name: "BlackGarurumon",
		stage: "Champion",
		types: ["DG-Water", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 96, atk: 53, def: 44, spa: 56, spd: 44, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	keramon: {
		num: -2176,
		name: "Keramon",
		stage: "Rookie",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 61, atk: 45, def: 43, spa: 43, spd: 56, spe: 38},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	chrysalimon: {
		num: -2177,
		name: "Chrysalimon",
		stage: "Champion",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 106, atk: 57, def: 70, spa: 68, spd: 80, spe: 26},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	infermon: {
		num: -2178,
		name: "Infermon",
		stage: "Ultimate",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 128, atk: 69, def: 71, spa: 80, spd: 77, spe: 58},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	diaboromon: {
		num: -2179,
		name: "Diaboromon",
		stage: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 168, atk: 97, def: 64, spa: 81, spd: 116, spe: 80},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	omnimon: {
		num: -2180,
		name: "Omnimon",
		stage: "Mega",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 196, atk: 106, def: 68, spa: 105, spd: 112, spe: 90},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	omnimonzwart: {
		num: -2181,
		name: "OmnimonZwart",
		stage: "Mega",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 196, atk: 116, def: 58, spa: 115, spd: 102, spe: 90},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
};

exports.BattlePokedex = BattlePokedex;
