"use strict";Object.defineProperty(exports, "__esModule", {value: true}); const Pokedex = {
	botamon: {
		num: -2000,
		name: "Botamon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 57, atk: 33, def: 23, spa: 38, spd: 18, spe: 20},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dodomon: {
		num: -2001,
		name: "Dodomon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 51, atk: 38, def: 22, spa: 37, spd: 38, spe: 18},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	kuramon: {
		num: -2002,
		name: "Kuramon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 58, atk: 27, def: 20, spa: 27, spd: 21, spe: 22},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.005,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	poyomon: {
		num: -2003,
		name: "Poyomon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 63, atk: 21, def: 24, spa: 30, spd: 31, spe: 19},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	punimon: {
		num: -2004,
		name: "Punimon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 55, atk: 42, def: 21, spa: 29, spd: 21, spe: 29},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	yuramon: {
		num: -2005,
		name: "Yuramon",
		stage: "Fresh",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 22, def: 29, spa: 18, spd: 29, spe: 20},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	bukamon: {
		num: -2006,
		name: "Bukamon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 62, atk: 36, def: 24, spa: 35, spd: 27, spe: 38},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.007,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	dorimon: {
		num: -2007,
		name: "Dorimon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 63, atk: 41, def: 30, spa: 40, spd: 30, spe: 24},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	koromon: {
		num: -2008,
		name: "Koromon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 62, atk: 43, def: 31, spa: 31, spd: 31, spe: 24},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	motimon: {
		num: -2009,
		name: "Motimon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 60, atk: 41, def: 27, spa: 41, spd: 28, spe: 25},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.008,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	nyaromon: {
		num: -2010,
		name: "Nyaromon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 63, atk: 36, def: 22, spa: 38, spd: 24, spe: 29},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.008,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tanemon: {
		num: -2011,
		name: "Tanemon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 61, atk: 36, def: 26, spa: 26, spd: 29, spe: 28},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	tokomon: {
		num: -2012,
		name: "Tokomon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 58, atk: 34, def: 24, spa: 34, spd: 27, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Tokomon-X"],
		formeOrder: ["Tokomon", "Tokomon-X"],
	},
	tsumemon: {
		num: -2013,
		name: "Tsumemon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 63, atk: 44, def: 27, spa: 44, spd: 28, spe: 27},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tsunomon: {
		num: -2014,
		name: "Tsunomon",
		stage: "In-Training",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 59, atk: 46, def: 28, spa: 33, spd: 28, spe: 32},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	agumon: {
		num: -2015,
		name: "Agumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 48, def: 36, spa: 36, spd: 31, spe: 33},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Agumon-X"],
		formeOrder: ["Agumon", "Agumon-X"],
	},
	aruraumon: {
		num: -2016,
		name: "Aruraumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 63, atk: 42, def: 36, spa: 41, spd: 36, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	betamon: {
		num: -2017,
		name: "Betamon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 49, atk: 44, def: 29, spa: 42, spd: 38, spe: 31},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Betamon-X"],
		formeOrder: ["Betamon", "Betamon-X"],
	},
	biyomon: {
		num: -2018,
		name: "Biyomon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 58, atk: 41, def: 31, spa: 41, spd: 29, spe: 42},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	blackagumon: {
		num: -2019,
		name: "BlackAgumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 64, atk: 49, def: 34, spa: 33, spd: 30, spe: 28},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
		otherFormes: ["BlackAgumon-X"],
		formeOrder: ["BlackAgumon", "BlackAgumon-X"],
	},
	blackgabumon: {
		num: -2020,
		name: "BlackGabumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 65, atk: 51, def: 32, spa: 45, spd: 33, spe: 31},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	clearagumon: {
		num: -2021,
		name: "ClearAgumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 64, atk: 45, def: 38, spa: 45, spd: 36, spe: 33},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	demidevimon: {
		num: -2022,
		name: "DemiDevimon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 58, atk: 42, def: 39, spa: 43, spd: 39, spe: 37},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.008,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dokunemon: {
		num: -2023,
		name: "Dokunemon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 62, atk: 46, def: 38, spa: 45, spd: 38, spe: 32},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	dorumon: {
		num: -2024,
		name: "Dorumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 74, atk: 46, def: 39, spa: 45, spd: 39, spe: 30},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	elecmon: {
		num: -2025,
		name: "Elecmon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 46, def: 30, spa: 44, spd: 30, spe: 29},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	gabumon: {
		num: -2026,
		name: "Gabumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Normal", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 34, spa: 48, spd: 34, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Gabumon-X"],
		formeOrder: ["Gabumon", "Gabumon-X"],
	},
	goburimon: {
		num: -2027,
		name: "Goburimon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 69, atk: 48, def: 42, spa: 38, spd: 38, spe: 29},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	gomamon: {
		num: -2028,
		name: "Gomamon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 63, atk: 43, def: 38, spa: 43, spd: 36, spe: 32},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Gomamon-X"],
		formeOrder: ["Gomamon", "Gomamon-X"],
	},
	gotsumon: {
		num: -2029,
		name: "Gotsumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 76, atk: 45, def: 46, spa: 47, spd: 35, spe: 28},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Gotsumon-X"],
		formeOrder: ["Gotsumon", "Gotsumon-X"],
	},
	keramon: {
		num: -2030,
		name: "Keramon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 61, atk: 45, def: 43, spa: 43, spd: 56, spe: 38},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Keramon-X"],
		formeOrder: ["Keramon", "Keramon-X"],
	},
	kunemon: {
		num: -2031,
		name: "Kunemon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 58, atk: 43, def: 39, spa: 42, spd: 39, spe: 30},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	modokibetamon: {
		num: -2032,
		name: "ModokiBetamon",
		universe: "Digimon",
		stage: "Rookie",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 47, atk: 45, def: 29, spa: 42, spd: 39, spe: 32},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	muchomon: {
		num: -2033,
		name: "Muchomon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 55, atk: 41, def: 31, spa: 41, spd: 29, spe: 41},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	otamamon: {
		num: -2034,
		name: "Otamamon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 61, atk: 43, def: 27, spa: 41, spd: 36, spe: 31},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Otamamon-X"],
		formeOrder: ["Otamamon", "Otamamon-X"],
	},
	palmon: {
		num: -2035,
		name: "Palmon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 60, atk: 43, def: 33, spa: 41, spd: 33, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Palmon-X"],
		formeOrder: ["Palmon", "Palmon-X"],
	},
	patamon: {
		num: -2036,
		name: "Patamon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 56, atk: 40, def: 32, spa: 38, spd: 32, spe: 44},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	penguinmon: {
		num: -2037,
		name: "Penguinmon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 43, def: 37, spa: 43, spd: 35, spe: 35},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	psychemon: {
		num: -2038,
		name: "Psychemon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 35, spa: 48, spd: 35, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	salamon: {
		num: -2039,
		name: "Salamon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 61, atk: 33, def: 32, spa: 44, spd: 34, spe: 35},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Salamon-X"],
		formeOrder: ["Salamon", "Salamon-X"],
	},
	shamanmon: {
		num: -2040,
		name: "Shamanmon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 68, atk: 43, def: 35, spa: 42, spd: 34, spe: 34},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	snowagumon: {
		num: -2041,
		name: "SnowAgumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 57, atk: 44, def: 38, spa: 33, spd: 33, spe: 31},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	snowgoburimon: {
		num: -2042,
		name: "SnowGoburimon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 46, def: 36, spa: 36, spd: 32, spe: 35},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	tentomon: {
		num: -2043,
		name: "Tentomon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 62, atk: 39, def: 41, spa: 43, spd: 35, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	toyagumon: {
		num: -2044,
		name: "ToyAgumon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 66, atk: 42, def: 41, spa: 42, spd: 39, spe: 32},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	tsukaimon: {
		num: -2045,
		name: "Tsukaimon",
		stage: "Rookie",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 59, atk: 41, def: 33, spa: 39, spd: 33, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	airdramon: {
		num: -2046,
		name: "Airdramon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 86, atk: 49, def: 54, spa: 47, spd: 53, spe: 55},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	akatorimon: {
		num: -2047,
		name: "Akatorimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 92, atk: 56, def: 54, spa: 56, spd: 47, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	angemon: {
		num: -2048,
		name: "Angemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 55, def: 45, spa: 55, spd: 43, spe: 51},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	bakemon: {
		num: -2049,
		name: "Bakemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 91, atk: 36, def: 49, spa: 50, spd: 54, spe: 49},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	birdramon: {
		num: -2050,
		name: "Birdramon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 43, spa: 53, spd: 42, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	blackgarurumon: {
		num: -2051,
		name: "BlackGarurumon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 96, atk: 53, def: 44, spa: 56, spd: 44, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackgatomon: {
		num: -2052,
		name: "BlackGatomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 85, atk: 42, def: 38, spa: 58, spd: 42, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
		blackgreymon: {
		num: -2053,
		name: "BlackGreymon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 98, atk: 68, def: 51, spa: 47, spd: 46, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	centarumon: {
		num: -2054,
		name: "Centarumon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 88, atk: 56, def: 56, spa: 56, spd: 49, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	chrysalimon: {
		num: -2055,
		name: "Chrysalimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 106, atk: 57, def: 70, spa: 68, spd: 80, spe: 26},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	coelamon: {
		num: -2056,
		name: "Coelamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 96, atk: 52, def: 50, spa: 45, spd: 44, spe: 47},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	darkrizamon: {
		num: -2057,
		name: "Darkrizamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 93, atk: 66, def: 47, spa: 66, spd: 54, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	devimon: {
		num: -2058,
		name: "Devimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 97, atk: 46, def: 43, spa: 63, spd: 48, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	dolphmon: {
		num: -2059,
		name: "Dolphmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 86, atk: 48, def: 50, spa: 48, spd: 43, spe: 50},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	dorugamon: {
		num: -2060,
		name: "Dorugamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 99, atk: 65, def: 59, spa: 63, spd: 58, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	drimogemon: {
		num: -2061,
		name: "Drimogemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 63, def: 55, spa: 55, spd: 48, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	flarerizamon: {
		num: -2062,
		name: "Flarerizamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 94, atk: 65, def: 45, spa: 65, spd: 52, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	frigimon: {
		num: -2063,
		name: "Frigimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 90, atk: 51, def: 59, spa: 51, spd: 58, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	fugamon: {
		num: -2064,
		name: "Fugamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 66, def: 50, spa: 67, spd: 50, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garurumon: {
		num: -2065,
		name: "Garurumon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 97, atk: 52, def: 46, spa: 59, spd: 45, spe: 48},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Garurumon-X"],
		formeOrder: ["Garurumon", "Garurumon-X"],
	},
	gatomon: {
		num: -2066,
		name: "Gatomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 88, atk: 42, def: 41, spa: 56, spd: 44, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Gatomon-X"],
		formeOrder: ["Gatomon", "Gatomon-X"],
	},
	gekomon: {
		num: -2067,
		name: "Gekomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 87, atk: 48, def: 46, spa: 48, spd: 49, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	geremon: {
		num: -2068,
		name: "Geremon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 57, spa: 54, spd: 57, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	greymon: {
		num: -2069,
		name: "Greymon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 99, atk: 67, def: 53, spa: 50, spd: 47, spe: 46},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Greymon-X"],
		formeOrder: ["Greymon", "Greymon-X"],
	},
	guardromon: {
		num: -2070,
		name: "Guardromon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 100, atk: 54, def: 60, spa: 62, spd: 45, spe: 42},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.032,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	gururumon: {
		num: -2071,
		name: "Gururumon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 94, atk: 52, def: 44, spa: 59, spd: 43, spe: 53},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	hyogamon: {
		num: -2072,
		name: "Hyogamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 96, atk: 65, def: 53, spa: 66, spd: 53, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	icedevimon: {
		num: -2073,
		name: "IceDevimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 94, atk: 59, def: 52, spa: 60, spd: 52, spe: 43},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.015,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	icemon: {
		num: -2074,
		name: "Icemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 93, atk: 46, def: 60, spa: 48, spd: 59, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ikkakumon: {
		num: -2075,
		name: "Ikkakumon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 99, atk: 69, def: 56, spa: 64, spd: 55, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	junglemojyamon: {
		num: -2076,
		name: "JungleMojyamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 94, atk: 61, def: 54, spa: 53, spd: 54, spe: 48},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	kabuterimon: {
		num: -2077,
		name: "Kabuterimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 98, atk: 55, def: 59, spa: 62, spd: 59, spe: 47},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	kokatorimon: {
		num: -2078,
		name: "Kokatorimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 59, def: 44, spa: 59, spd: 38, spe: 46},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	kuwagamon: {
		num: -2079,
		name: "Kuwagamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 42, spa: 64, spd: 42, spe: 48},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Kuwagamon-X"],
		formeOrder: ["Kuwagamon", "Kuwagamon-X"],
	},
	leomon: {
		num: -2080,
		name: "Leomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 69, def: 45, spa: 52, spd: 40, spe: 43},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Leomon-X"],
		formeOrder: ["Leomon", "Leomon-X"],
	},
	meicoomon: {
		num: -2081,
		name: "Meicoomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 85, atk: 59, def: 40, spa: 59, spd: 41, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meramon: {
		num: -2082,
		name: "Meramon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 99, atk: 70, def: 41, spa: 51, spd: 36, spe: 44},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Meramon-X"],
		formeOrder: ["Meramon", "Meramon-X"],
	},
	mikemon: {
		num: -2083,
		name: "Mikemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 90, atk: 43, def: 41, spa: 57, spd: 44, spe: 46},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	mojyamon: {
		num: -2084,
		name: "Mojyamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 92, atk: 55, def: 59, spa: 48, spd: 59, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	monochromon: {
		num: -2085,
		name: "Monochromon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 99, atk: 66, def: 58, spa: 58, spd: 50, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Monochromon-X"],
		formeOrder: ["Monochromon", "Monochromon-X"],
	},
	morishellmon: {
		num: -2086,
		name: "MoriShellmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 96, atk: 59, def: 58, spa: 59, spd: 51, spe: 39},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	mudfrigimon: {
		num: -2087,
		name: "MudFrigimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 89, atk: 55, def: 58, spa: 55, spd: 56, spe: 38},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	nanimon: {
		num: -2088,
		name: "Nanimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 93, atk: 54, def: 49, spa: 62, spd: 37, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	ninjamon: {
		num: -2089,
		name: "Ninjamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 45, spa: 55, spd: 45, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.015,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	nisedrimogemon: {
		num: -2090,
		name: "NiseDrimogemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 95, atk: 54, def: 53, spa: 47, spd: 46, spe: 44},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	numemon: {
		num: -2091,
		name: "Numemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 83, atk: 48, def: 42, spa: 44, spd: 56, spe: 40},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Numemon-X"],
		formeOrder: ["Numemon", "Numemon-X"],
	},
	ogremon: {
		num: -2092,
		name: "Ogremon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 66, def: 55, spa: 67, spd: 55, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Ogremon-X"],
		formeOrder: ["Ogremon", "Ogremon-X"],
	},
	piddomon: {
		num: -2093,
		name: "Piddomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 87, atk: 59, def: 46, spa: 55, spd: 45, spe: 49},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	platinumsukamon: {
		num: -2094,
		name: "PlatinumSukamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Poison", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 55, spa: 61, spd: 57, spe: 39},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	redvegiemon: {
		num: -2095,
		name: "RedVegiemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 93, atk: 59, def: 47, spa: 61, spd: 47, spe: 44},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.012,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	rockmon: {
		num: -2096,
		name: "Rockmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 93, atk: 61, def: 52, spa: 61, spd: 50, spe: 33},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	saberdramon: {
		num: -2097,
		name: "Saberdramon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 86, atk: 66, def: 42, spa: 55, spd: 41, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	sandyanmamon: {
		num: -2098,
		name: "SandYanmamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 91, atk: 46, def: 60, spa: 53, spd: 53, spe: 44},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	seadramon: {
		num: -2099,
		name: "Seadramon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 88, atk: 60, def: 52, spa: 61, spd: 55, spe: 42},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.021,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Seadramon-X"],
		formeOrder: ["Seadramon", "Seadramon-X"],
	},
	shellmon: {
		num: -2100,
		name: "Shellmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 59, spa: 60, spd: 52, spe: 36},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shimaunimon: {
		num: -2101,
		name: "ShimaUnimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 81, atk: 54, def: 43, spa: 61, spd: 38, spe: 52},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	soulmon: {
		num: -2102,
		name: "Soulmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 91, atk: 29, def: 48, spa: 58, spd: 58, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	sukamon: {
		num: -2103,
		name: "Sukamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 92, atk: 48, def: 51, spa: 49, spd: 51, spe: 45},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tankmon: {
		num: -2104,
		name: "Tankmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 100, atk: 60, def: 59, spa: 65, spd: 44, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.035,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	togemon: {
		num: -2105,
		name: "Togemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 63, def: 56, spa: 61, spd: 56, spe: 41},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Togemon-X"],
		formeOrder: ["Togemon", "Togemon-X"],
	},
	tyrannomon: {
		num: -2106,
		name: "Tyrannomon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 65, def: 45, spa: 63, spd: 45, spe: 43},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Tyrannomon-X"],
		formeOrder: ["Tyrannomon", "Tyrannomon-X"],
	},
	unimon: {
		num: -2107,
		name: "Unimon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 56, def: 43, spa: 56, spd: 38, spe: 50},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.3,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	vegiemon: {
		num: -2108,
		name: "Vegiemon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 89, atk: 46, def: 54, spa: 48, spd: 54, spe: 42},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	weedmon: {
		num: -2109,
		name: "Weedmon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Grass", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 90, atk: 59, def: 48, spa: 60, spd: 48, spe: 41},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	yanmamon: {
		num: -2110,
		name: "Yanmamon",
		stage: "Champion",
		universe: "Digimon",
		types: ["DG-Electric"],
		gender: "N",
		baseStats: {hp: 87, atk: 53, def: 47, spa: 60, spd: 41, spe: 46},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	andromon: {
		num: -2111,
		name: "Andromon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 125, atk: 69, def: 72, spa: 76, spd: 53, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	angewomon: {
		num: -2112,
		name: "Angewomon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 129, atk: 57, def: 52, spa: 76, spd: 57, spe: 66},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Angewomon-X"],
		formeOrder: ["Angewomon", "Angewomon-X"],
	},
	beastmon: {
		num: -2113,
		name: "Beastmon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 120, atk: 79, def: 52, spa: 69, spd: 46, spe: 70},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	blackweregarurumon: {
		num: -2114,
		name: "BlackWereGarurumon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 128, atk: 75, def: 67, spa: 76, spd: 67, spe: 66},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	bluemeramon: {
		num: -2115,
		name: "BlueMeramon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Water"],
		gender: "N",
		baseStats: {hp: 137, atk: 76, def: 57, spa: 77, spd: 57, spe: 62},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	digitamamon: {
		num: -2116,
		name: "Digitamamon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 130, atk: 69, def: 76, spa: 51, spd: 68, spe: 50},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	dorugreymon: {
		num: -2117,
		name: "DoruGreymon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 135, atk: 79, def: 71, spa: 77, spd: 70, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.036,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	etemon: {
		num: -2118,
		name: "Etemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 119, atk: 66, def: 73, spa: 67, spd: 73, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	garudamon: {
		num: -2119,
		name: "Garudamon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 125, atk: 75, def: 58, spa: 75, spd: 57, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Garudamon-X"],
		formeOrder: ["Garudamon", "Garudamon-X"],
	},
	gigadramon: {
		num: -2120,
		name: "Gigadramon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 134, atk: 72, def: 73, spa: 81, spd: 55, spe: 61},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	giromon: {
		num: -2121,
		name: "Giromon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 125, atk: 81, def: 60, spa: 71, spd: 60, spe: 56},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	iceleomon: {
		num: -2122,
		name: "IceLeomon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 130, atk: 88, def: 60, spa: 66, spd: 53, spe: 58},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["IceLeomon-X"],
		formeOrder: ["IceLeomon", "IceLeomon-X"],
	},
	infermon: {
		num: -2123,
		name: "Infermon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 128, atk: 69, def: 71, spa: 80, spd: 77, spe: 58},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ladydevimon: {
		num: -2124,
		name: "LadyDevimon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 126, atk: 58, def: 54, spa: 78, spd: 60, spe: 63},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
		otherFormes: ["LadyDevimon-X"],
		formeOrder: ["LadyDevimon", "LadyDevimon-X"],
	},
	lillymon: {
		num: -2125,
		name: "Lillymon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 122, atk: 65, def: 63, spa: 65, spd: 63, spe: 66},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.016,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Lillymon-X"],
		formeOrder: ["Lillymon", "Lillymon-X"],
	},
	magnaangemon: {
		num: -2126,
		name: "MagnaAngemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 128, atk: 77, def: 46, spa: 70, spd: 60, spe: 66},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	mamemon: {
		num: -2127,
		name: "Mamemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 127, atk: 68, def: 68, spa: 75, spd: 51, spe: 59},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Mamemon-X"],
		formeOrder: ["Mamemon", "Mamemon-X"],
	},
	megadramon: {
		num: -2128,
		name: "Megadramon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 131, atk: 79, def: 68, spa: 60, spd: 61, spe: 56},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	megakabuterimon: {
		num: -2129,
		name: "MegaKabuterimon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 139, atk: 79, def: 70, spa: 59, spd: 62, spe: 55},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	megaseadramon: {
		num: -2130,
		name: "MegaSeadramon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 75, def: 61, spa: 74, spd: 61, spe: 60},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["MegaSeadramon-X"],
		formeOrder: ["MegaSeadramon", "MegaSeadramon-X"],
	},
	meicrackmon: {
		num: -2131,
		name: "Meicrackmon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 110, atk: 77, def: 53, spa: 75, spd: 53, spe: 68},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	meicrackmonvm: {
		num: -2132,
		name: "Meicrackmon VM",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 110, atk: 77, def: 53, spa: 75, spd: 53, spe: 68},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	metalgreymonvaccine: {
		num: -2133,
		name: "MetalGreymon Vaccine",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		otherFormes: ["MetalGreymon Vaccine-X"],
		formeOrder: ["MetalGreymon Vaccine", "MetalGreymon Vaccine-X"],
	},
	metalgreymonvirus: {
		num: -2134,
		name: "MetalGreymon Virus",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["MetalGreymon Virus-X"],
		formeOrder: ["MetalGreymon Virus", "MetalGreymon Virus-X"],
	},
	metalmamemon: {
		num: -2135,
		name: "MetalMamemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 123, atk: 76, def: 69, spa: 75, spd: 69, spe: 62},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		otherFormes: ["MetalMamemon-X"],
		formeOrder: ["MetalMamemon", "MetalMamemon-X"],
	},
	meteormon: {
		num: -2136,
		name: "Meteormon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 135, atk: 65, def: 75, spa: 70, spd: 56, spe: 63},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	monzaemon: {
		num: -2137,
		name: "Monzaemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 134, atk: 53, def: 65, spa: 72, spd: 71, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Monzaemon-X"],
		formeOrder: ["Monzaemon", "Monzaemon-X"],
	},
	myotismon: {
		num: -2138,
		name: "Myotismon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 136, atk: 57, def: 63, spa: 77, spd: 70, spe: 55},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Myotismon-X"],
		formeOrder: ["Myotismon", "Myotismon-X"],
	},
	piximon: {
		num: -2139,
		name: "Piximon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fairy"],
		gender: "N",
		baseStats: {hp: 118, atk: 65, def: 63, spa: 64, spd: 63, spe: 65},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	shogungekomon: {
		num: -2140,
		name: "ShogunGekomon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 72, def: 73, spa: 74, spd: 73, spe: 51},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	skullgreymon: {
		num: -2141,
		name: "SkullGreymon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 138, atk: 85, def: 73, spa: 65, spd: 66, spe: 52},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	tekkamon: {
		num: -2142,
		name: "Tekkamon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 123, atk: 70, def: 67, spa: 62, spd: 67, spe: 60},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.05,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	vademon: {
		num: -2143,
		name: "Vademon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 119, atk: 78, def: 52, spa: 72, spd: 69, spe: 53},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Vademon-X"],
		formeOrder: ["Vademon", "Vademon-X"],
	},
	vermilimon: {
		num: -2144,
		name: "Vermilimon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 130, atk: 78, def: 73, spa: 68, spd: 64, spe: 57},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	warumonzaemon: {
		num: -2145,
		name: "WaruMonzaemon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 133, atk: 53, def: 64, spa: 72, spd: 70, spe: 55},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.024,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	waruseadramon: {
		num: -2146,
		name: "WaruSeadramon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 58, def: 56, spa: 77, spd: 61, spe: 59},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	weregarurumon: {
		num: -2147,
		name: "WereGarurumon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 127, atk: 74, def: 59, spa: 74, spd: 58, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.018,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	whamon: {
		num: -2148,
		name: "Whamon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 140, atk: 75, def: 71, spa: 75, spd: 70, spe: 52},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	zudomon: {
		num: -2149,
		name: "Zudomon",
		stage: "Ultimate",
		universe: "Digimon",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 137, atk: 80, def: 72, spa: 80, spd: 70, spe: 51},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	alphamon: {
		num: -2150,
		name: "Alphamon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 185, atk: 107, def: 101, spa: 107, spd: 98, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.07,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackmetalgarurumon: {
		num: -2151,
		name: "BlackMetalGarurumon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Water"],
		gender: "N",
		baseStats: {hp: 184, atk: 99, def: 66, spa: 90, spd: 50, spe: 79},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.028,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	blackwargreymon: {
		num: -2152,
		name: "BlackWarGreymon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 188, atk: 101, def: 81, spa: 78, spd: 69, spe: 74},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
		otherFormes: ["BlackWarGreymon-X"],
		formeOrder: ["BlackWarGreymon", "BlackWarGreymon-X"],
	},
	boltmon: {
		num: -2153,
		name: "Boltmon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 191, atk: 100, def: 84, spa: 75, spd: 76, spe: 73},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
	cherubimonevil: {
		num: -2154,
		name: "Cherubimon Evil",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 195, atk: 106, def: 63, spa: 96, spd: 86, spe: 78},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.035,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Cherubimon Evil-X"],
		formeOrder: ["Cherubimon Evil", "Cherubimon Evil-X"],
	},
	cherubimongood: {
		num: -2155,
		name: "Cherubimon Good",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 183, atk: 102, def: 69, spa: 92, spd: 92, spe: 75},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Cherubimon Good-X"],
		formeOrder: ["Cherubimon Good", "Cherubimon Good-X"],
	},
	devitamamon: {
		num: -2156,
		name: "Devitamamon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Poison", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 184, atk: 99, def: 87, spa: 97, spd: 87, spe: 76},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	diaboromon: {
		num: -2157,
		name: "Diaboromon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 168, atk: 97, def: 64, spa: 81, spd: 116, spe: 80},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Diaboromon-X"],
		formeOrder: ["Diaboromon", "Diaboromon-X"],
	},
	dorugoramon: {
		num: -2158,
		name: "Dorugoramon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 188, atk: 101, def: 83, spa: 99, spd: 100, spe: 72},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.064,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	ebemon: {
		num: -2159,
		name: "Ebemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Steel", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 184, atk: 76, def: 67, spa: 98, spd: 79, spe: 66},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Ebemon-X"],
		formeOrder: ["Ebemon", "Ebemon-X"],
	},
	herculeskabuterimon: {
		num: -2160,
		name: "HerculesKabuterimon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 188, atk: 89, def: 91, spa: 104, spd: 90, spe: 80},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["HerculesKabuterimon-X"],
		formeOrder: ["HerculesKabuterimon", "HerculesKabuterimon-X"],
	},
	hiandromon: {
		num: -2161,
		name: "HiAndromon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 181, atk: 97, def: 82, spa: 87, spd: 61, spe: 74},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	lilithmon: {
		num: -2162,
		name: "Lilithmon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 191, atk: 58, def: 69, spa: 104, spd: 89, spe: 80},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Lilithmon-X"],
		formeOrder: ["Lilithmon", "Lilithmon-X"],
	},
	machinedramon: {
		num: -2163,
		name: "Machinedramon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 189, atk: 90, def: 86, spa: 101, spd: 65, spe: 72},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	magnadramon: {
		num: -2164,
		name: "Magnadramon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 190, atk: 102, def: 84, spa: 101, spd: 87, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Magnadramon-X"],
		formeOrder: ["Magnadramon", "Magnadramon-X"],
	},
	marineangemon: {
		num: -2165,
		name: "MarineAngemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Water", "DG-Fairy"],
		gender: "N",
		baseStats: {hp: 170, atk: 52, def: 72, spa: 82, spd: 71, spe: 75},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.005,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	metaletemon: {
		num: -2166,
		name: "MetalEtemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Poison", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 171, atk: 75, def: 84, spa: 84, spd: 63, spe: 69},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
	},
	metalgarurumon: {
		num: -2167,
		name: "MetalGarurumon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 182, atk: 97, def: 70, spa: 96, spd: 70, spe: 76},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.028,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		otherFormes: ["MetalGarurumon-X"],
		formeOrder: ["MetalGarurumon", "MetalGarurumon-X"],
	},
	metalseadramon: {
		num: -2168,
		name: "MetalSeadramon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 185, atk: 94, def: 62, spa: 83, spd: 82, spe: 70},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	omnimon: {
		num: -2169,
		name: "Omnimon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 196, atk: 106, def: 68, spa: 105, spd: 112, spe: 90},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Omnimon-X"],
		formeOrder: ["Omnimon", "Omnimon-X"],
	},
	omnimonzwart: {
		num: -2170,
		name: "OmnimonZwart",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 196, atk: 116, def: 58, spa: 115, spd: 102, spe: 90},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
	},
	ophanimon: {
		num: -2171,
		name: "Ophanimon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 180, atk: 72, def: 86, spa: 104, spd: 85, spe: 80},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Ophanimon-X"],
		formeOrder: ["Ophanimon", "Ophanimon-X"],
	},
	phoenixmon: {
		num: -2172,
		name: "Phoenixmon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 190, atk: 75, def: 75, spa: 100, spd: 82, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Phoenixmon-X"],
		formeOrder: ["Phoenixmon", "Phoenixmon-X"],
	},
	princemamemon: {
		num: -2173,
		name: "PrinceMamemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 175, atk: 83, def: 87, spa: 82, spd: 87, spe: 69},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["PrinceMamemon-X"],
		formeOrder: ["PrinceMamemon", "PrinceMamemon-X"],
	},
	raguelmon: {
		num: -2174,
		name: "Raguelmon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 188, atk: 95, def: 66, spa: 92, spd: 101, spe: 84},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Brown",
		eggGroups: ["Undiscovered"],
	},
	rasielmon: {
		num: -2175,
		name: "Rasielmon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 189, atk: 92, def: 66, spa: 95, spd: 101, spe: 84},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	rosemon: {
		num: -2176,
		name: "Rosemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 171, atk: 89, def: 69, spa: 88, spd: 69, spe: 75},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.019,
		color: "Red",
		eggGroups: ["Undiscovered"],
		otherFormes: ["Rosemon-X"],
		formeOrder: ["Rosemon", "Rosemon-X"],
	},
	saberleomon: {
		num: -2177,
		name: "SaberLeomon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 182, atk: 98, def: 70, spa: 97, spd: 70, spe: 77},
		abilities: {0: "Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	seraphimon: {
		num: -2178,
		name: "Seraphimon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 185, atk: 96, def: 62, spa: 107, spd: 81, spe: 82},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
	},
	venommyotismon: {
		num: -2179,
		name: "VenomMyotismon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 190, atk: 105, def: 92, spa: 80, spd: 82, spe: 70},
		abilities: {0: "Virus"},
		heightm: 1,
		weightkg: 0.038,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	vikemon: {
		num: -2180,
		name: "Vikemon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 193, atk: 100, def: 85, spa: 90, spd: 77, spe: 67},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	wargreymon: {
		num: -2181,
		name: "WarGreymon",
		stage: "Mega",
		universe: "Digimon",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 187, atk: 100, def: 85, spa: 75, spd: 76, spe: 71},
		abilities: {0: "Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		otherFormes: ["WarGreymon-X"],
		formeOrder: ["WarGreymon", "WarGreymon-X"],
	},
	tokomonx: {
		num: -3000,
		name: "Tokomon-X",
		basename: "Tokomon",
		stage: "In-Training",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 58, atk: 34, def: 24, spa: 34, spd: 27, spe: 36},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	agumonx: {
		num: -3001,
		name: "Agumon-X",
		basename: "Agumon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 65, atk: 48, def: 36, spa: 36, spd: 31, spe: 33},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	betamonx: {
		num: -3002,
		name: "Betamon-X",
		basename: "Betamon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 49, atk: 44, def: 29, spa: 42, spd: 38, spe: 31},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	blackagumonx: {
		num: -3003,
		name: "BlackAgumon-X",
		basename: "BlackAgumon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 64, atk: 49, def: 34, spa: 33, spd: 30, spe: 28},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	gabumonx: {
		num: -3004,
		name: "Gabumon-X",
		basename: "Gabumon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Normal", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 66, atk: 50, def: 34, spa: 48, spd: 34, spe: 36},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	gomamonx: {
		num: -3005,
		name: "Gomamon-X",
		basename: "Gomamon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 63, atk: 43, def: 38, spa: 43, spd: 36, spe: 32},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	gotsumonx: {
		num: -3006,
		name: "Gotsumon-X",
		basename: "Gotsumon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 76, atk: 45, def: 46, spa: 47, spd: 35, spe: 28},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	keramonx: {
		num: -3007,
		name: "Keramon-X",
		basename: "Keramon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 61, atk: 45, def: 43, spa: 43, spd: 56, spe: 38},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	otamamonx: {
		num: -3008,
		name: "Otamamon-X",
		basename: "Otamamon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 61, atk: 43, def: 27, spa: 41, spd: 36, spe: 31},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	palmonx: {
		num: -3009,
		name: "Palmon-X",
		basename: "Palmon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 60, atk: 43, def: 33, spa: 41, spd: 33, spe: 35},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.015,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	salamonx: {
		num: -3010,
		name: "Salamon-X",
		basename: "Salamon",
		stage: "Rookie",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 61, atk: 33, def: 32, spa: 44, spd: 34, spe: 35},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.012,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	garurumonx: {
		num: -3011,
		name: "Garurumon-X",
		basename: "Garurumon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 97, atk: 52, def: 46, spa: 59, spd: 45, spe: 48},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	gatomonx: {
		num: -3012,
		name: "Gatomon-X",
		basename: "Gatomon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 88, atk: 42, def: 41, spa: 56, spd: 44, spe: 49},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	greymonx: {
		num: -3013,
		name: "Greymon-X",
		basename: "Greymon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 99, atk: 67, def: 53, spa: 50, spd: 47, spe: 46},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	kuwagamonx: {
		num: -3014,
		name: "Kuwagamon-X",
		basename: "Kuwagamon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 93, atk: 62, def: 42, spa: 64, spd: 42, spe: 48},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	leomonx: {
		num: -3015,
		name: "Leomon-X",
		basename: "Leomon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 69, def: 45, spa: 52, spd: 40, spe: 43},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	meramonx: {
		num: -3016,
		name: "Meramon-X",
		basename: "Meramon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 99, atk: 70, def: 41, spa: 51, spd: 36, spe: 44},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.018,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	monochromonx: {
		num: -3017,
		name: "Monochromon-X",
		basename: "Monochromon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 99, atk: 66, def: 58, spa: 58, spd: 50, spe: 42},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	numemonx: {
		num: -3018,
		name: "Numemon-X",
		basename: "Numemon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 83, atk: 48, def: 42, spa: 44, spd: 56, spe: 40},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.01,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	ogremonx: {
		num: -3019,
		name: "Ogremon-X",
		basename: "Ogremon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 66, def: 55, spa: 67, spd: 55, spe: 41},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	seadramonx: {
		num: -3020,
		name: "Seadramon-X",
		basename: "Seadramon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 88, atk: 60, def: 52, spa: 61, spd: 55, spe: 42},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.021,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	togemonx: {
		num: -3021,
		name: "Togemon-X",
		basename: "Togemon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 97, atk: 63, def: 56, spa: 61, spd: 56, spe: 41},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	tyrannomonx: {
		num: -3022,
		name: "Tyrannomon-X",
		basename: "Tyrannomon",
		stage: "Champion",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 98, atk: 65, def: 45, spa: 63, spd: 45, spe: 43},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	angewomonx: {
		num: -3023,
		name: "Angewomon-X",
		basename: "Angewomon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 129, atk: 57, def: 52, spa: 76, spd: 57, spe: 66},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	garudamonx: {
		num: -3024,
		name: "Garudamon-X",
		basename: "Garudamon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 125, atk: 75, def: 58, spa: 75, spd: 57, spe: 67},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	iceleomonx: {
		num: -3025,
		name: "IceLeomon-X",
		basename: "IceLeomon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Normal", "DG-Water"],
		gender: "N",
		baseStats: {hp: 130, atk: 88, def: 60, spa: 66, spd: 53, spe: 58},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	ladydevimonx: {
		num: -3026,
		name: "LadyDevimon-X",
		basename: "LadyDevimon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 126, atk: 58, def: 54, spa: 78, spd: 60, spe: 63},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Black",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	lillymonx: {
		num: -3027,
		name: "Lillymon-X",
		basename: "Lillymon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 122, atk: 65, def: 63, spa: 65, spd: 63, spe: 66},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	mamemonx: {
		num: -3028,
		name: "Mamemon-X",
		basename: "Mamemon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Normal"],
		gender: "N",
		baseStats: {hp: 127, atk: 68, def: 68, spa: 75, spd: 51, spe: 59},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	megaseadramonx: {
		num: -3029,
		name: "MegaSeadramon-X",
		basename: "MegaSeadramon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water"],
		gender: "N",
		baseStats: {hp: 131, atk: 75, def: 61, spa: 74, spd: 61, spe: 60},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.025,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	metalgreymonvaccinex: {
		num: -3030,
		name: "MetalGreymon Vaccine-X",
		basename: "MetalGreymon Vaccine",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	metalgreymonvirusx: {
		num: -3031,
		name: "MetalGreymon Virus-X",
		basename: "MetalGreymon Virus",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Dark"],
		gender: "N",
		baseStats: {hp: 130, atk: 79, def: 68, spa: 59, spd: 60, spe: 58},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.04,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	metalmamemonx: {
		num: -3032,
		name: "MetalMamemon-X",
		basename: "MetalMamemon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Steel"],
		gender: "N",
		baseStats: {hp: 123, atk: 76, def: 69, spa: 75, spd: 69, spe: 62},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.005,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	monzaemonx: {
		num: -3033,
		name: "Monzaemon-X",
		basename: "Monzaemon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 134, atk: 53, def: 65, spa: 72, spd: 71, spe: 52},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.04,
		color: "Brown",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	myotismonx: {
		num: -3034,
		name: "Myotismon-X",
		basename: "Myotismon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 136, atk: 57, def: 63, spa: 77, spd: 70, spe: 55},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.018,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	vademonx: {
		num: -3035,
		name: "Vademon-X",
		basename: "Vademon",
		stage: "Ultimate",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Poison"],
		gender: "N",
		baseStats: {hp: 119, atk: 78, def: 52, spa: 72, spd: 69, spe: 53},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	blackwargreymonx: {
		num: -3036,
		name: "BlackWarGreymon-X",
		basename: "BlackWarGreymon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 188, atk: 101, def: 81, spa: 78, spd: 69, spe: 74},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Black",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	cherubimonevilx: {
		num: -3037,
		name: "Cherubimon Evil-X",
		basename: "Cherubimon Evil",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 195, atk: 106, def: 63, spa: 96, spd: 86, spe: 78},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.035,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	cherubimongoodx: {
		num: -3038,
		name: "Cherubimon Good-X",
		basename: "Cherubimon Good",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 183, atk: 102, def: 69, spa: 92, spd: 92, spe: 75},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.035,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	diaboromonx: {
		num: -3039,
		name: "Diaboromon-X",
		basename: "Diaboromon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 168, atk: 97, def: 64, spa: 81, spd: 116, spe: 80},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.03,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	ebemonx: {
		num: -3040,
		name: "Ebemon-X",
		basename: "Ebemon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Steel", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 184, atk: 76, def: 67, spa: 98, spd: 79, spe: 66},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.02,
		color: "Gray",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	herculeskabuterimonx: {
		num: -3041,
		name: "HerculesKabuterimon-X",
		basename: "HerculesKabuterimon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Electric", "DG-Grass"],
		gender: "N",
		baseStats: {hp: 188, atk: 89, def: 91, spa: 104, spd: 90, spe: 80},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	phoenixmonx: {
		num: -3041,
		name: "Phoenixmon-X",
		basename: "Phoenixmon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Electric", "DG-Fire"],
		gender: "N",
		baseStats: {hp: 190, atk: 75, def: 75, spa: 100, spd: 82, spe: 82},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	lilithmonx: {
		num: -3042,
		name: "Lilithmon-X",
		basename: "Lilithmon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Dark"],
		gender: "N",
		baseStats: {hp: 191, atk: 58, def: 69, spa: 104, spd: 89, spe: 80},
		abilities: {0: "X-Virus"},
		heightm: 1,
		weightkg: 0.025,
		color: "Purple",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	magnadramonx: {
		num: -3043,
		name: "Magnadramon-X",
		basename: "Magnadramon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy"],
		gender: "N",
		baseStats: {hp: 190, atk: 102, def: 84, spa: 101, spd: 87, spe: 82},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Pink",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	metalgarurumonx: {
		num: -3044,
		name: "MetalGarurumon-X",
		basename: "MetalGarurumon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Water", "DG-Steel"],
		gender: "N",
		baseStats: {hp: 182, atk: 97, def: 70, spa: 96, spd: 70, spe: 76},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.028,
		color: "Blue",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	omnimonx: {
		num: -3045,
		name: "Omnimon-X",
		basename: "Omnimon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 196, atk: 106, def: 68, spa: 105, spd: 112, spe: 90},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "White",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	ophanimonx: {
		num: -3046,
		name: "Ophanimon-X",
		basename: "Ophanimon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy", "DG-Electric"],
		gender: "N",
		baseStats: {hp: 180, atk: 72, def: 86, spa: 104, spd: 85, spe: 80},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.02,
		color: "Green",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	princemamemonx: {
		num: -3047,
		name: "PrinceMamemon-X",
		basename: "PrinceMamemon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fairy", "DG-Poison"],
		gender: "N",
		baseStats: {hp: 175, atk: 83, def: 87, spa: 82, spd: 87, spe: 69},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.01,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	rosemonx: {
		num: -3048,
		name: "Rosemon-X",
		basename: "Rosemon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Grass"],
		gender: "N",
		baseStats: {hp: 171, atk: 89, def: 69, spa: 88, spd: 69, spe: 75},
		abilities: {0: "X-Data"},
		heightm: 1,
		weightkg: 0.019,
		color: "Red",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	wargreymonx: {
		num: -3049,
		name: "WarGreymon-X",
		basename: "WarGreymon",
		stage: "Mega",
		universe: "Digimon",
		forme: "Mega",
		types: ["DG-Fire", "DG-Normal"],
		gender: "N",
		baseStats: {hp: 187, atk: 100, def: 85, spa: 75, spd: 76, spe: 71},
		abilities: {0: "X-Vaccine"},
		heightm: 1,
		weightkg: 0.03,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
		requiredItem: "X-Antibody",
	},
	bulbasaur: {
		inherit: true,
		universe: "Pokemon",
	},
	ivysaur: {
		inherit: true,
		universe: "Pokemon",
	},
	venusaur: {
		inherit: true,
		universe: "Pokemon",
	},
	venusaurmega: {
		inherit: true,
		universe: "Pokemon",
	},
	charmander: {
		inherit: true,
		universe: "Pokemon",
	},
	charmeleon: {
		inherit: true,
		universe: "Pokemon",
	},
	charizard: {
		inherit: true,
		universe: "Pokemon",
	},
	charizardmegax: {
		inherit: true,
		universe: "Pokemon",
	},
	charizardmegay: {
		inherit: true,
		universe: "Pokemon",
	},
	squirtle: {
		inherit: true,
		universe: "Pokemon",
	},
	wartortle: {
		inherit: true,
		universe: "Pokemon",
	},
	blastoise: {
		inherit: true,
		universe: "Pokemon",
	},
	blastoisemega: {
		inherit: true,
		universe: "Pokemon",
	},
	caterpie: {
		inherit: true,
		universe: "Pokemon",
	},
	metapod: {
		inherit: true,
		universe: "Pokemon",
	},
	butterfree: {
		inherit: true,
		universe: "Pokemon",
	},
	weedle: {
		inherit: true,
		universe: "Pokemon",
	},
	kakuna: {
		inherit: true,
		universe: "Pokemon",
	},
	beedrill: {
		inherit: true,
		universe: "Pokemon",
	},
	beedrillmega: {
		inherit: true,
		universe: "Pokemon",
	},
	pidgey: {
		inherit: true,
		universe: "Pokemon",
	},
	pidgeotto: {
		inherit: true,
		universe: "Pokemon",
	},
	pidgeot: {
		inherit: true,
		universe: "Pokemon",
	},
	pidgeotmega: {
		inherit: true,
		universe: "Pokemon",
	},
	rattata: {
		inherit: true,
		universe: "Pokemon",
	},
	rattataalola: {
		inherit: true,
		universe: "Pokemon",
	},
	raticate: {
		inherit: true,
		universe: "Pokemon",
	},
	raticatealola: {
		inherit: true,
		universe: "Pokemon",
	},
	spearow: {
		inherit: true,
		universe: "Pokemon",
	},
	fearow: {
		inherit: true,
		universe: "Pokemon",
	},
	ekans: {
		inherit: true,
		universe: "Pokemon",
	},
	arbok: {
		inherit: true,
		universe: "Pokemon",
	},
	pikachu: {
		inherit: true,
		universe: "Pokemon",
	},
	pikachustarter: {
		inherit: true,
		universe: "Pokemon",
	},
	raichu: {
		inherit: true,
		universe: "Pokemon",
	},
	raichualola: {
		inherit: true,
		universe: "Pokemon",
	},
	sandshrew: {
		inherit: true,
		universe: "Pokemon",
	},
	sandshrewalola: {
		inherit: true,
		universe: "Pokemon",
	},
	sandslash: {
		inherit: true,
		universe: "Pokemon",
	},
	sandslashalola: {
		inherit: true,
		universe: "Pokemon",
	},
	nidoranf: {
		inherit: true,
		universe: "Pokemon",
	},
	nidorina: {
		inherit: true,
		universe: "Pokemon",
	},
	nidoqueen: {
		inherit: true,
		universe: "Pokemon",
	},
	nidoranm: {
		inherit: true,
		universe: "Pokemon",
	},
	nidorino: {
		inherit: true,
		universe: "Pokemon",
	},
	nidoking: {
		inherit: true,
		universe: "Pokemon",
	},
	clefairy: {
		inherit: true,
		universe: "Pokemon",
	},
	clefable: {
		inherit: true,
		universe: "Pokemon",
	},
	vulpix: {
		inherit: true,
		universe: "Pokemon",
	},
	vulpixalola: {
		inherit: true,
		universe: "Pokemon",
	},
	ninetales: {
		inherit: true,
		universe: "Pokemon",
	},
	ninetalesalola: {
		inherit: true,
		universe: "Pokemon",
	},
	jigglypuff: {
		inherit: true,
		universe: "Pokemon",
	},
	wigglytuff: {
		inherit: true,
		universe: "Pokemon",
	},
	zubat: {
		inherit: true,
		universe: "Pokemon",
	},
	golbat: {
		inherit: true,
		universe: "Pokemon",
	},
	oddish: {
		inherit: true,
		universe: "Pokemon",
	},
	gloom: {
		inherit: true,
		universe: "Pokemon",
	},
	vileplume: {
		inherit: true,
		universe: "Pokemon",
	},
	paras: {
		inherit: true,
		universe: "Pokemon",
	},
	parasect: {
		inherit: true,
		universe: "Pokemon",
	},
	venonat: {
		inherit: true,
		universe: "Pokemon",
	},
	venomoth: {
		inherit: true,
		universe: "Pokemon",
	},
	diglett: {
		inherit: true,
		universe: "Pokemon",
	},
	diglettalola: {
		inherit: true,
		universe: "Pokemon",
	},
	dugtrio: {
		inherit: true,
		universe: "Pokemon",
	},
	dugtrioalola: {
		inherit: true,
		universe: "Pokemon",
	},
	meowth: {
		inherit: true,
		universe: "Pokemon",
	},
	meowthalola: {
		inherit: true,
		universe: "Pokemon",
	},
	persian: {
		inherit: true,
		universe: "Pokemon",
	},
	persianalola: {
		inherit: true,
		universe: "Pokemon",
	},
	psyduck: {
		inherit: true,
		universe: "Pokemon",
	},
	golduck: {
		inherit: true,
		universe: "Pokemon",
	},
	mankey: {
		inherit: true,
		universe: "Pokemon",
	},
	primeape: {
		inherit: true,
		universe: "Pokemon",
	},
	growlithe: {
		inherit: true,
		universe: "Pokemon",
	},
	arcanine: {
		inherit: true,
		universe: "Pokemon",
	},
	poliwag: {
		inherit: true,
		universe: "Pokemon",
	},
	poliwhirl: {
		inherit: true,
		universe: "Pokemon",
	},
	poliwrath: {
		inherit: true,
		universe: "Pokemon",
	},
	abra: {
		inherit: true,
		universe: "Pokemon",
	},
	kadabra: {
		inherit: true,
		universe: "Pokemon",
	},
	alakazam: {
		inherit: true,
		universe: "Pokemon",
	},
	alakazammega: {
		inherit: true,
		universe: "Pokemon",
	},
	machop: {
		inherit: true,
		universe: "Pokemon",
	},
	machoke: {
		inherit: true,
		universe: "Pokemon",
	},
	machamp: {
		inherit: true,
		universe: "Pokemon",
	},
	bellsprout: {
		inherit: true,
		universe: "Pokemon",
	},
	weepinbell: {
		inherit: true,
		universe: "Pokemon",
	},
	victreebel: {
		inherit: true,
		universe: "Pokemon",
	},
	tentacool: {
		inherit: true,
		universe: "Pokemon",
	},
	tentacruel: {
		inherit: true,
		universe: "Pokemon",
	},
	geodude: {
		inherit: true,
		universe: "Pokemon",
	},
	geodudealola: {
		inherit: true,
		universe: "Pokemon",
	},
	graveler: {
		inherit: true,
		universe: "Pokemon",
	},
	graveleralola: {
		inherit: true,
		universe: "Pokemon",
	},
	golem: {
		inherit: true,
		universe: "Pokemon",
	},
	golemalola: {
		inherit: true,
		universe: "Pokemon",
	},
	ponyta: {
		inherit: true,
		universe: "Pokemon",
	},
	rapidash: {
		inherit: true,
		universe: "Pokemon",
	},
	slowpoke: {
		inherit: true,
		universe: "Pokemon",
	},
	slowbro: {
		inherit: true,
		universe: "Pokemon",
	},
	slowbromega: {
		inherit: true,
		universe: "Pokemon",
	},
	magnemite: {
		inherit: true,
		universe: "Pokemon",
	},
	magneton: {
		inherit: true,
		universe: "Pokemon",
	},
	farfetchd: {
		inherit: true,
		universe: "Pokemon",
	},
	doduo: {
		inherit: true,
		universe: "Pokemon",
	},
	dodrio: {
		inherit: true,
		universe: "Pokemon",
	},
	seel: {
		inherit: true,
		universe: "Pokemon",
	},
	dewgong: {
		inherit: true,
		universe: "Pokemon",
	},
	grimer: {
		inherit: true,
		universe: "Pokemon",
	},
	grimeralola: {
		inherit: true,
		universe: "Pokemon",
	},
	muk: {
		inherit: true,
		universe: "Pokemon",
	},
	mukalola: {
		inherit: true,
		universe: "Pokemon",
	},
	shellder: {
		inherit: true,
		universe: "Pokemon",
	},
	cloyster: {
		inherit: true,
		universe: "Pokemon",
	},
	gastly: {
		inherit: true,
		universe: "Pokemon",
	},
	haunter: {
		inherit: true,
		universe: "Pokemon",
	},
	gengar: {
		inherit: true,
		universe: "Pokemon",
	},
	gengarmega: {
		inherit: true,
		universe: "Pokemon",
	},
	onix: {
		inherit: true,
		universe: "Pokemon",
	},
	drowzee: {
		inherit: true,
		universe: "Pokemon",
	},
	hypno: {
		inherit: true,
		universe: "Pokemon",
	},
	krabby: {
		inherit: true,
		universe: "Pokemon",
	},
	kingler: {
		inherit: true,
		universe: "Pokemon",
	},
	voltorb: {
		inherit: true,
		universe: "Pokemon",
	},
	electrode: {
		inherit: true,
		universe: "Pokemon",
	},
	exeggcute: {
		inherit: true,
		universe: "Pokemon",
	},
	exeggutor: {
		inherit: true,
		universe: "Pokemon",
	},
	exeggutoralola: {
		inherit: true,
		universe: "Pokemon",
	},
	cubone: {
		inherit: true,
		universe: "Pokemon",
	},
	marowak: {
		inherit: true,
		universe: "Pokemon",
	},
	marowakalola: {
		inherit: true,
		universe: "Pokemon",
	},
	hitmonlee: {
		inherit: true,
		universe: "Pokemon",
	},
	hitmonchan: {
		inherit: true,
		universe: "Pokemon",
	},
	lickitung: {
		inherit: true,
		universe: "Pokemon",
	},
	koffing: {
		inherit: true,
		universe: "Pokemon",
	},
	weezing: {
		inherit: true,
		universe: "Pokemon",
	},
	rhyhorn: {
		inherit: true,
		universe: "Pokemon",
	},
	rhydon: {
		inherit: true,
		universe: "Pokemon",
	},
	chansey: {
		inherit: true,
		universe: "Pokemon",
	},
	tangela: {
		inherit: true,
		universe: "Pokemon",
	},
	kangaskhan: {
		inherit: true,
		universe: "Pokemon",
	},
	kangaskhanmega: {
		inherit: true,
		universe: "Pokemon",
	},
	horsea: {
		inherit: true,
		universe: "Pokemon",
	},
	seadra: {
		inherit: true,
		universe: "Pokemon",
	},
	goldeen: {
		inherit: true,
		universe: "Pokemon",
	},
	seaking: {
		inherit: true,
		universe: "Pokemon",
	},
	staryu: {
		inherit: true,
		universe: "Pokemon",
	},
	starmie: {
		inherit: true,
		universe: "Pokemon",
	},
	mrmime: {
		inherit: true,
		universe: "Pokemon",
	},
	scyther: {
		inherit: true,
		universe: "Pokemon",
	},
	jynx: {
		inherit: true,
		universe: "Pokemon",
	},
	electabuzz: {
		inherit: true,
		universe: "Pokemon",
	},
	magmar: {
		inherit: true,
		universe: "Pokemon",
	},
	pinsir: {
		inherit: true,
		universe: "Pokemon",
	},
	pinsirmega: {
		inherit: true,
		universe: "Pokemon",
	},
	tauros: {
		inherit: true,
		universe: "Pokemon",
	},
	magikarp: {
		inherit: true,
		universe: "Pokemon",
	},
	gyarados: {
		inherit: true,
		universe: "Pokemon",
	},
	gyaradosmega: {
		inherit: true,
		universe: "Pokemon",
	},
	lapras: {
		inherit: true,
		universe: "Pokemon",
	},
	ditto: {
		inherit: true,
		universe: "Pokemon",
	},
	eevee: {
		inherit: true,
		universe: "Pokemon",
	},
	eeveestarter: {
		inherit: true,
		universe: "Pokemon",
	},
	vaporeon: {
		inherit: true,
		universe: "Pokemon",
	},
	jolteon: {
		inherit: true,
		universe: "Pokemon",
	},
	flareon: {
		inherit: true,
		universe: "Pokemon",
	},
	porygon: {
		inherit: true,
		universe: "Pokemon",
	},
	omanyte: {
		inherit: true,
		universe: "Pokemon",
	},
	omastar: {
		inherit: true,
		universe: "Pokemon",
	},
	kabuto: {
		inherit: true,
		universe: "Pokemon",
	},
	kabutops: {
		inherit: true,
		universe: "Pokemon",
	},
	aerodactyl: {
		inherit: true,
		universe: "Pokemon",
	},
	aerodactylmega: {
		inherit: true,
		universe: "Pokemon",
	},
	snorlax: {
		inherit: true,
		universe: "Pokemon",
	},
	articuno: {
		inherit: true,
		universe: "Pokemon",
	},
	zapdos: {
		inherit: true,
		universe: "Pokemon",
	},
	moltres: {
		inherit: true,
		universe: "Pokemon",
	},
	dratini: {
		inherit: true,
		universe: "Pokemon",
	},
	dragonair: {
		inherit: true,
		universe: "Pokemon",
	},
	dragonite: {
		inherit: true,
		universe: "Pokemon",
	},
	mewtwo: {
		inherit: true,
		universe: "Pokemon",
	},
	mewtwomegax: {
		inherit: true,
		universe: "Pokemon",
	},
	mewtwomegay: {
		inherit: true,
		universe: "Pokemon",
	},
	mew: {
		inherit: true,
		universe: "Pokemon",
	},
	meltan: {
			inherit: true,
			universe: "Pokemon",
	},
	melmetal: {
		inherit: true,
		universe: "Pokemon",
	},
}; exports.Pokedex = Pokedex;